### ISSUE TITLE
Suport JSON output for desanitizer

### ISSUE THREAD

**Issue by mrdavidlaing** [pivotal-cloudops/secrets-sanitizer#19]
JSON is valid YAML.  Some secrets we store are stored in JSON.  Namely the terraform `.tfstate`.  

Add a --json flag to desanitize so  that we can have this functionality.

```
$ desanitize -i terraform.tfstate -s secrets-terraform.tfstate.json --json
```

Should interpolate the secrets back into terraform.tfstate and write terraform.tfstate as json (not as YAML as is the default) 

please note that YAML has a .to_json function

**Comment by supertopher** [comment]
we overcame this limitation by making the secrets YAML then 

`desanitize -s secret -i input | yml2json | jq > yourcoolsecret.json` it works pretty well actually
