### ISSUE TITLE
When passing a single argument for secrets UX is non-intuitive

### ISSUE THREAD

**Issue by supertopher** [pivotal-cloudops/secrets-sanitizer#20]
When passing a single secrets file we still check for a file name match.  This should perhaps be a warning, but we should also trust that the user knows what they are doing.

ie: i rename a yaml file.  i then ask desanitizer to desan my renamed file with the correct secrets.json

i expect desanitizer to desanitize this file... however it does not.  

talk to @mrdavidlaing or myself if this is confusing <3

**Comment by landesherr** [comment]
Unable to reproduce with the latest version of secrets-sanitizer.
See https://www.pivotaltracker.com/story/show/130369635 for details
