### ISSUE TITLE
desanitize skips unquoted curly brackets

### ISSUE THREAD

**Issue by BenChapman** [pivotal-cloudops/secrets-sanitizer#21]
Hey guys,

We ran into an issue when trying to use this against a new deployment where we had set up the secrets first and then generated the manifest.

It desanitized unquoted secrets incorrectly, and didn't output any errors.

This 

```
  password: {{password}}
```

became:

```
        ? password: 
        : 
```

It desanitized perfectly once the curly brackets were quoted 

```
  password: "{{password}}"
```

**Comment by supertopher** [comment]
We are aware of this, but i'm not sure that we are going to fix it.  The escape characters we look for are `"{{` We actually started out with only `{{` we found though: if you perform any YAML transformations (ie: spiff) you essentially have an invalid hash and therefore invalid YAML while the manifest is sanitized.  Many of our systems need to perform spiff merges on sanitized manifests.

Especially given that you created the secrets file by handi feel like fixing this problem will create more problems than it solves.  I'm always open to having my mind changed though.  If you think there is a need for this syntax please explain to me what that need it.  Also thanks for taking the time to bring this to our attention.  👍

**Comment by supertopher** [comment]
I do agree however that this does seem like a problem that is likely to be encountered by other.  Perhaps we can have a warning for `{{`... without a preceding `"` would that have made the experience better for you?

**Comment by tushar-dadlani** [comment]
Using curly braces will break the yaml 1.2 spec.
It doesn't really make sense to fix this, as Topher said. It may make sense to use ((...)) instead of curly braces, but it may also make sense to abandon the whole thing because we're using credhub.
