### ISSUE TITLE
Separate YAML linter step (preprocess?)

### ISSUE THREAD

**Issue by pronoiac** [pivotal-cloudops/secrets-sanitizer#3]
When we run the sanitizer / templatizer, it has two effects: 
- the main one: it takes out the secrets
- secondary: it normalizes the yaml, adding quotes to strings, fixing indentation, etc. 

The secondary effect is like a YAML linter, and it would be nice to be able to do _just that step:_ if we break up the whole thing a little bit, it could make verifying the first step easier. One could lint, commit, then take out secrets, and there would be less noise in the diff from the normalization.

**Comment by supertopher** [comment]
if you still feel this is an issue please reopen this @pronoiac 

just cleaning up issues that aren't prioritized
