### ISSUE TITLE
Use environment variables

### ISSUE THREAD

**Issue by pronoiac** [pivotal-cloudops/secrets-sanitizer#6]
There's a way we could run `desanitizer` without arguments and have it do the right thing. 

[direnv](http://direnv.net/) could set the appropriate secrets subfolder. (We could also use a `~/.sanitizer` for recording the secrets repo/folder, if we want to keep that less public.) 

It would involve less typing, more automation, and fewer mistakes.

**Comment by supertopher** [comment]
we have addressed this issue with defaults on master
